### ISSUE TITLE
Pages that have ended

### ISSUE THREAD

**Issue by Abbassihraf** [Zineb112/2AI-project#16]
Hello,

I would like to inform you that the meeting with  @Rim-Bennani  will be via **_Skype_**
_**At approximately 3pm on Monday July 20, 2020**_.

### The points to be discussed:

1. Display the first version of pages that have ended.
2. The project progress.
3. Determine the completion date of the development of the first part of website.
**`Meeting link, it'll be added soon.`**

**Please confirm your presence, thank you.**

**Best regards.**

**`N.B: Try to finish the first part of website before July 21,2020`**

**Comment by Salma-hu** [comment]
Je confirme ma présence

**Comment by MinaDakiri12** [comment]
I finish my section partners and now i'm working in contact page , for call with @Rim-Bennani i'm present

**Comment by Zineb112** [comment]
I'm still working on newsletter and Portail de l'Innovation section. For monday's call i'm present
