### ISSUE TITLE
Portail De L'inventeur functionality

### ISSUE THREAD

**Issue by Abbassihraf** [Zineb112/2AI-project#49]
### Portail De L'inventeur  back-end

- [x] Populate the table with data 
- [x] Functionality for displaying last 3 portail in the home page C2 from db order by time
- [x] Functionality for displaying portail in portail page from db order by time
- [x] Functionality for displaying portail in the portail page from db 
- [x] Functionality for adding portail to the db
- [x] Functionality for updating portail  from the db
- [x] Functionality for deleting  portail  from the db
- [x] Security and refactor code

**Comment by Zineb112** [comment]
@Abbassihraf  check my work pls

**Comment by Abbassihraf** [comment]
@Zineb112  Everything work good.
