### ISSUE TITLE
2AI News functionality

### ISSUE THREAD

**Issue by Abbassihraf** [Zineb112/2AI-project#50]
### 2AI News back-end

- [x] Populate the table with data 
- [x] Functionality for displaying the last 2AI News from db into homeC2 page order by time
- [x] Functionality for displaying 2AI News from db into 2ai news page order by time
- [x] Functionality for adding 2AI News to the db
- [x] Functionality for updating 2AI News from the db
- [x] Functionality for deleting  2AI News from the db
- [x] Security and refactor code

**Comment by MinaDakiri12** [comment]
@Abbassihraf @Salma-hu @Zineb112 check my last functions
 Functionality for displaying the last 2AI News from db into homeC2 page order by time
 Functionality for displaying 2AI News from db into 2ai news page order by time
