### ISSUE TITLE
Carnet de l'inventeur

### ISSUE THREAD

**Issue by Abbassihraf** [Zineb112/2AI-project#55]
- [x] Add input for uploading the file 
- [x] Edit displaying div for DATE input

**Comment by Salma-hu** [comment]
@Abbassihraf 

- I am facing a problem with the download button as it does not download the intended file

**Comment by Salma-hu** [comment]
@Abbassihraf @MinaDakiri12 @Zineb112  check my  task

**Comment by Abbassihraf** [comment]
Ok, I'll test it
