### ISSUE TITLE
Realization of the site's high fidelity Wireframe.

### ISSUE THREAD

**Issue by Zineb112** [Zineb112/2AI-project#6]
- [x] Home page : Desktop version
- [x] Contact page : Desktop version
- [x] Team page : Desktop version
- [x] About us page : Desktop version
- [x] Galerie : Desktop version
- [x] Blog page : Desktop version
- [x] Blog post page : Desktop version

**Comment by Abbassihraf** [comment]
Review done with @Rim-Bennani about page home.

**Comment by Abbassihraf** [comment]
Review done with @Rim-Bennani about team page.

**Comment by Abbassihraf** [comment]
Review done with @Rim-Bennani concerning about us page.

**Comment by Abbassihraf** [comment]
Review done with @Rim-Bennani concerning CONTACT page.

**Comment by Abbassihraf** [comment]
Review done with @Rim-Bennani concerning GALLERY page.

**Comment by Abbassihraf** [comment]
Review done with @Rim-Bennani concerning NEWS page.

**Comment by Abbassihraf** [comment]
Review done with @Rim-Bennani concerning NEWS POST page.
